### ISSUE TITLE
Other Elements

### ISSUE THREAD

**Issue by joshua1** [edvail/elm-polymer#1]
Hi @edvail i stumbled on this package today and am most impressed. I wanted to ask if you have plans to implement the other polymer element groups like iron, gold and neon ,as well as the 2.0 versions. I also wish to know how this can be used alongside third party polymer components without the need to include polymer reference in the index.html file that are already included in this package

**Comment by ed-ilyin** [comment]
This module just makes html tags available in Elm. But you anyway have to install elements using bower and import them in html.
I'm adding elements as soon as I need them in my projects.

You are very welcome to fork this repository and make a PR (pull request).
Just look inside, there is no magic, all is straight forward. :)

**Comment by joshua1** [comment]
Thanks @edvail
