### ISSUE TITLE
Error trying to use package

### ISSUE THREAD

**Issue by joshua1** [edvail/elm-polymer#2]
@edvail 
When i run elm-make i get the below error 

```
I cannot find module 'Polymer.Paper'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```

what am i missing please.
Thanks

**Comment by ed-ilyin** [comment]
probably you need to install module first:
`elm package install edvail/elm-polymer`

**Comment by joshua1** [comment]
Thanks @edvail i did that already. i think your response to #1 already answers both questions.
